# Uncomment the next line to define a global platform for your project
# platform :macos, '10.0'

target 'EasyMagicChartDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'KSCrash'
  pod 'SDWebImage'

  # Pods for EasyMagicChartDemo

end

